no_of_weeks_per_line: 2

color:
  week: [0.3, 0.3, 0.3]
  highlight: [0.3, 0.3, 0.3]

highlight:
  mode: 'bold'
  weekdays: [6, 7]

font:
  caption: 'Century Gothic'
  month: 'Broadway'
  week: 'Century Gothic'
  day: 'Century Gothic'

geometry:
  grid:
    row_height: 4
