language: 'de'
no_of_weeks_per_line: 1
weekday_long_form: false

font:
  month: 'Garamond'
  week: 'Arial'
  day: 'Arial'

color:
  month: [0, 0, 0]
  week: [0, 0, 0]
  day: [0, 0, 0]

geometry:
  paper:
    width: 300
    height: 300
    margins:
      top: 20
      bottom: 20
      left: 10
      right: 20
  grid:
    month_width: 0.4
    mid_padding: 0.05
    row_height: 4
